name: Mongo Replica

on:
  push:
    branches: [main]
    tags: ["*"]

jobs:
  dockerize:
    environment: docker-hub
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Docker Login
        run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        env:
          DOCKER_USERNAME: notholst
          DOCKER_PASSWORD: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Build container image
        run: docker buildx build --platform linux/amd64,linux/arm64 -t littlegiants/mongo-replica:${{github.ref_name}} --push .
